name: app
description: Logistics app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  localization: ^2.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  otp_text_field: ^1.1.3
  flutter_pw_validator: ^1.6.0
  get: ^4.6.5
  syncfusion_flutter_sliders: ^22.1.38
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_credit_card: ^3.0.7
  shared_preferences: ^2.0.12
  http: ^1.1.0
  hive: ^2.2.3
  intl: ^0.18.1
  font_awesome_flutter: ^10.5.0
  fl_chart: ^0.63.0
  syncfusion_flutter_datagrid: ^22.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/SVN-Gilroy Regular.otf
        - asset: assets/fonts/SVN-Gilroy Bold.otf
          weight: 700
        - asset: assets/fonts/SVN-Gilroy XBold.otf
          weight: 800
        - asset: assets/fonts/SVN-Gilroy Light.otf
          weight: 300
        - asset: assets/fonts/SVN-Gilroy Medium.otf
          weight: 500
        - asset: assets/fonts/SVN-Gilroy SemiBold.otf
          weight: 600
        - asset: assets/fonts/SVN-Gilroy Thin.otf
          weight: 100
  assets:
    - assets/images/login.png

